# -*- coding: utf-8 -*-

{
    'name': "Lingjack Print",
    'author': "Alitec Pte Ltd",
    'website': "http://www.alitec.sg",
    'category': 'Alitec',
    'version': '18.0.0.1.66',
    'description': """
    - Last Update: 05-FEB-2026
    """,
    'depends': ['base', 'lingjack_operation'],
    'data': [
        # 'reports/layout.xml',
        'data/paperformate.xml',
        'views/account_invoice_report_view.xml',
        'reports/report.xml',
        'reports/external_layout_standard.xml',
        'reports/report_payment_receipt.xml',
        'reports/delivery_slip.xml',
        'reports/quality_certificate.xml',
        'reports/conformity_certificate.xml',
        'reports/product_limited_warranty.xml',
        'reports/origin_certificate.xml',
        'reports/beneficiary_cerificate.xml',
        'reports/shipment_advice.xml',
        'reports/confirmation_manufacturer.xml',
        'reports/picking_list.xml',
        'reports/purchase_order_report.xml',
        'reports/sale_quotations.xml',
        'reports/report_journal_voucher.xml',
        'reports/report_proforma_invoice.xml',
        'reports/tax_invoice.xml',
        'reports/report_export_invoice.xml',
        'reports/report_packing_list.xml',
        'reports/chamber_coo_invoice_report.xml',
        'reports/invoice_delivery_report.xml',
        'reports/receiving_incoming_label.xml',
        'reports/report_commercial_invoice.xml',
        'reports/report_export_tax_invoice.xml',
        'reports/report_production_incoming_layout.xml',
        'reports/report_invoice_delivery.xml',
        'reports/report_export_invoice_do.xml',
        'reports/debit_note_report.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
